name: Deploy on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set Git identity
      - name: Set Git identity
        run: |
          git config --global user.email "matinanad@gmail.com"
          git config --global user.name "matinanadali"

      # Step 3: Run deploy script
      - name: Run deploy script
        run: npm run deploy
